### ISSUE TITLE
MovableType7にてゴミ箱に入れた記事が表示されません

### ISSUE THREAD

**Issue by FreeBSE** [masiuchi/mt-plugin-trash#5]
MovableType 7にて記事一覧から指定した記事をゴミ箱に入れると
データベース上では、きちんとtrashカラムが追加され
値も1になっていたのでゴミ箱としての処理は出来てるようなのですが
記事ゴミ箱のところから見ても記事一覧と同じ表示がされ
ゴミ箱に入れた記事が表示されなくなります。
Plack上で確認しました。

よろしくお願いします。

**Comment by masiuchi** [comment]
コメントありがとうございます。
MT7 にはまだ対応できておりません。申し訳ありません。
対応検討いたします。

**Comment by FreeBSE** [comment]
よろしくお願いします！

**Comment by masiuchi** [comment]
@FreeBSE 
MT7 対応しました。

**Comment by FreeBSE** [comment]
お忙しい中、対応ありがとうございました！
動作確認出来ました！

**Comment by masiuchi** [comment]
良かったです。本件はクローズします。
また何かございましたらいつでもコメントください。
